### ISSUE TITLE
Temperature & Humidity Sensor | Hide Humidity values

### ISSUE THREAD

**Issue by Gobastos** [dkerr64/homebridge-yolink#7]
**Is your feature request related to a problem? Please describe:**

I am currently using the "Temperature and Humidity Sensor with probe" to measure the temperature of my swimming pool.
The probe is immersed in the swimming pool water and for this use case it doesn't make sense to read the humidity (altough the humidity readings are always zero which doesn't make sense either)

**Describe the solution you'd like:**

It would be useful if we could somehow hide the readings of one of the sensors (temperature or humidity depending on the use you're giving to your sensor) to avoid these readings being displayed in the Apple Home app when they doesn't make sense (in my use case the humidity is always zero)

**Describe alternatives you've considered:**

**Additional context:**

**Comment by dkerr64** [comment]
I think the best way to do this is to suppress the Hydrometer "service" so that it doesn't even appear in Homebridge / HomeKit.  I think there are two options.

1. provide for a configuration setting.  I could extend the "hide" from a boolean true/false to allow for "true, false, hydro, thermo" for example.  Then in your case we could set "hide": "thermo" in the config.
2. or if there is a way to automatically detect in the JSON returned then we could do that.

I think that the first option is probably best / easiest / most reliable / most flexible.  But I don't know what happens to existing config files if I change the type from boolean, will have to test that... I'd hate to break existing installs.

Thoughts?

**Comment by Gobastos** [comment]
Hi David
Indeed the first option would be the best.
In order no not break existing installs, wouldn't be possible to have this new configuration parameter as optional, meaning if it is not set, is assumes true by default for both services and if it is set, it assumes the boolean value specified ?
Thanks.
Guilherme

**Comment by dkerr64** [comment]
I just published an update with this feature added.  Thanks for the suggestion.

**Comment by Gobastos** [comment]
Many Thanks David,
It's working perfectly
Best Regards, Guilherme
